package com.drops.pos;
import android.app.*;import android.os.*;import android.content.*;import android.database.*;import android.database.sqlite.*;import android.graphics.*;import android.graphics.Typeface;import android.view.*;import android.widget.*;import java.util.*;

public class MainActivity extends Activity{
 DB db; LinearLayout root,body; final int NAVY=0xff071426,BG=0xfff1f5f9,BLUE=0xff2563eb,GREEN=0xff16a34a,RED=0xffdc2626; LinkedHashMap<Long,Integer> cart=new LinkedHashMap<>();
 int dp(float x){return(int)(x*getResources().getDisplayMetrics().density+.5f);}
 TextView t(String s,int z,int c,boolean b){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setPadding(dp(14),dp(10),dp(14),dp(10));if(b)v.setTypeface(null,Typeface.BOLD);return v;}
 public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(NAVY);getWindow().setNavigationBarColor(NAVY);if(Build.VERSION.SDK_INT>=23)getWindow().getDecorView().setSystemUiVisibility(0);db=new DB(this);home();}
 void shell(String p,String sub){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);LinearLayout h=new LinearLayout(this);h.setOrientation(LinearLayout.VERTICAL);h.setBackgroundColor(NAVY);h.setPadding(dp(18),dp(22),dp(18),dp(14));h.addView(t("DROPS POS",24,Color.WHITE,true));h.addView(t(p,16,0xff93c5fd,true));h.addView(t(sub,12,0xffcbd5e1,false));root.addView(h);ScrollView sv=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(14),dp(14),dp(14),dp(26));sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));LinearLayout n=new LinearLayout(this);n.setPadding(dp(4),dp(4),dp(4),dp(4));n.setBackgroundColor(Color.WHITE);nav(n,"الرئيسية",()->home());nav(n,"بيع",()->pos());nav(n,"المنتجات",()->products());nav(n,"التقارير",()->reports());root.addView(n,new LinearLayout.LayoutParams(-1,dp(66)));setContentView(root);}
 android.graphics.drawable.GradientDrawable bg(int color,float radius){android.graphics.drawable.GradientDrawable g=new android.graphics.drawable.GradientDrawable();g.setColor(color);g.setCornerRadius(dp(radius));return g;}
 void nav(LinearLayout n,String s,Runnable r){TextView b=t(s,12,NAVY,true);b.setGravity(Gravity.CENTER);b.setOnClickListener(v->r.run());n.addView(b,new LinearLayout.LayoutParams(0,-1,1));}
 void card(String a,String b,String c){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setPadding(dp(4),dp(4),dp(4),dp(4));x.setBackground(bg(Color.WHITE,18));x.setElevation(dp(2));x.addView(t(a,13,0xff64748b,true));x.addView(t(b,25,NAVY,true));x.addView(t(c,12,0xff64748b,false));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,0,0,dp(12));body.addView(x,lp);}
 void btn(String s,Runnable r){TextView b=t(s,15,Color.WHITE,true);b.setGravity(Gravity.CENTER);b.setBackground(bg(BLUE,16));b.setElevation(dp(2));b.setOnClickListener(v->r.run());LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(56));lp.setMargins(0,0,0,dp(10));body.addView(b,lp);}
 void section(String s){TextView v=t(s,16,NAVY,true);v.setPadding(dp(4),dp(16),dp(4),dp(10));body.addView(v);}
 void home(){shell("لوحة التحكم","Drops Detergents  •  FULL BUILD  •  USD/LBP 90,000");double s=db.todaySales();section("نظرة سريعة");card("مبيعات اليوم","$ "+fmt(s),lbp(s)+" LBP  •  "+db.todayCount()+" فاتورة");card("قيمة المخزون","$ "+fmt(db.stockValue()),db.productCount()+" منتج مسجل");card("تنبيهات المخزون",""+db.lowCount(),"منتجات وصلت إلى الحد الأدنى");section("عمليات سريعة");btn("🛒  فاتورة بيع جديدة",()->pos());btn("📦  إدخال مخزون",()->stockIn());btn("↕  حركات المخزون",()->stockMoves());btn("＋  إضافة منتج جديد",()->productDialog());btn("💵  تسجيل مصروف",()->expenseDialog());btn("🏭  التصنيع والمواد الأولية",()->manufacturing());section("الإدارة");btn("👥  العملاء",()->people("العملاء","customer"));btn("🚚  الموردون",()->people("الموردون","supplier"));btn("📋  سجل الفواتير",()->invoices());btn("⚙  الإعدادات",()->settings());}
 void products(){shell("المنتجات","إدارة السعر والكمية والحذف");Cursor c=db.getProducts();while(c.moveToNext()){final long id=c.getLong(0);String name=c.getString(1),size=c.getString(2);double price=c.getDouble(3);int qty=c.getInt(4);card(name+" • "+size,"$ "+fmt(price),"Stock: "+qty+" • "+lbp(price)+" LBP");btn("تعديل — "+name,()->editProduct(id));}c.close();btn("＋ منتج جديد",()->productDialog());}
 void productDialog(){LinearLayout l=form();EditText n=e("اسم المنتج"),s=e("الحجم مثال 1L"),p=e("سعر البيع USD"),q=e("الكمية");l.addView(n);l.addView(s);l.addView(p);l.addView(q);new AlertDialog.Builder(this).setTitle("منتج جديد").setView(l).setPositiveButton("حفظ",(d,w)->{try{db.addProduct(n.getText().toString(),s.getText().toString(),Double.parseDouble(p.getText().toString()),Integer.parseInt(q.getText().toString()));products();}catch(Exception ex){toast("راجع البيانات");}}).setNegativeButton("إلغاء",null).show();}
 void editProduct(long id){Cursor c=db.one(id);if(!c.moveToFirst())return;String name=c.getString(1);LinearLayout l=form();EditText p=e("السعر"),q=e("الكمية");p.setText(""+c.getDouble(3));q.setText(""+c.getInt(4));l.addView(p);l.addView(q);c.close();new AlertDialog.Builder(this).setTitle("تعديل "+name).setView(l).setPositiveButton("حفظ",(d,w)->{try{db.updateProduct(id,Double.parseDouble(p.getText().toString()),Integer.parseInt(q.getText().toString()));products();}catch(Exception x){toast("راجع البيانات");}}).setNeutralButton("حذف",(d,w)->{db.deleteProduct(id);products();}).setNegativeButton("إلغاء",null).show();}
 void stockMoves(){shell("حركات المخزون","دخول • بيع • تسوية");Cursor c=db.stockMoves();while(c.moveToNext()){String q=(c.getInt(3)>0?"+":"")+c.getInt(3);card(c.getString(1)+" • "+c.getString(2),q+" قطعة",c.getString(4));}c.close();}
 void stockIn(){Cursor c=db.getProducts();ArrayList<Long> ids=new ArrayList<>();ArrayList<String> names=new ArrayList<>();while(c.moveToNext()){ids.add(c.getLong(0));names.add(c.getString(1)+" "+c.getString(2));}c.close();if(ids.size()==0){toast("أضف منتج أولاً");return;}new AlertDialog.Builder(this).setTitle("اختر المنتج").setItems(names.toArray(new String[0]),(d,i)->qtyDialog(ids.get(i))).show();}
 void qtyDialog(long id){EditText q=e("الكمية الداخلة");new AlertDialog.Builder(this).setTitle("إدخال مخزون").setView(q).setPositiveButton("إضافة",(d,w)->{try{db.addStock(id,Integer.parseInt(q.getText().toString()));home();}catch(Exception x){toast("كمية غير صحيحة");}}).setNegativeButton("إلغاء",null).show();}
 void pos(){shell("نقطة البيع","أضف عدة منتجات للسلة ثم احفظ الفاتورة");Cursor c=db.getProducts();while(c.moveToNext()){final long id=c.getLong(0);String name=c.getString(1)+" • "+c.getString(2);double price=c.getDouble(3);int qty=c.getInt(4);int in=cart.containsKey(id)?cart.get(id):0;btn("＋ "+name+"   $"+fmt(price)+"   مخزون "+qty+(in>0?"   [بالسلة "+in+"]":""),()->addCart(id));}c.close();double total=cartTotal();card("إجمالي السلة","$ "+fmt(total),lbp(total)+" LBP • "+cartQty()+" قطعة");if(cartQty()>0){btn("عرض / تعديل السلة",()->showCart());btn("✓ حفظ الفاتورة",()->checkout());btn("مسح السلة",()->{cart.clear();pos();});}}
 void addCart(long id){Cursor c=db.one(id);if(!c.moveToFirst())return;int st=c.getInt(4);c.close();int q=cart.containsKey(id)?cart.get(id):0;if(q>=st){toast("لا يوجد مخزون إضافي");return;}cart.put(id,q+1);pos();}
 void showCart(){ArrayList<Long> ids=new ArrayList<>(cart.keySet());ArrayList<String> rows=new ArrayList<>();for(long id:ids){Cursor c=db.one(id);if(c.moveToFirst())rows.add(c.getString(1)+" "+c.getString(2)+" × "+cart.get(id));c.close();}new AlertDialog.Builder(this).setTitle("السلة — اضغط لحذف قطعة").setItems(rows.toArray(new String[0]),(d,i)->{long id=ids.get(i);int q=cart.get(id)-1;if(q<=0)cart.remove(id);else cart.put(id,q);pos();}).setPositiveButton("إغلاق",null).show();}
 void checkout(){if(cartQty()==0)return;LinearLayout l=form();EditText paid=e("المبلغ المدفوع USD (اختياري)");l.addView(paid);new AlertDialog.Builder(this).setTitle("تأكيد الفاتورة • $ "+fmt(cartTotal())).setView(l).setPositiveButton("حفظ",(d,w)->{double p=0;try{if(paid.getText().length()>0)p=Double.parseDouble(paid.getText().toString());}catch(Exception x){}long no=db.checkout(cart,p);if(no>0){cart.clear();toast("تم حفظ الفاتورة #"+no);home();}else toast("راجع كميات المخزون");}).setNegativeButton("إلغاء",null).show();}
 double cartTotal(){double x=0;for(Map.Entry<Long,Integer>a:cart.entrySet()){Cursor c=db.one(a.getKey());if(c.moveToFirst())x+=c.getDouble(3)*a.getValue();c.close();}return x;}int cartQty(){int x=0;for(int q:cart.values())x+=q;return x;}
 void manufacturing(){shell("التصنيع","مواد أولية • إنتاج • تكلفة");card("المواد الأولية",""+db.rawCount()+" مادة","إدارة الكميات والتكلفة");btn("＋ إضافة مادة أولية",()->rawDialog());Cursor c=db.rawMaterials();while(c.moveToNext())card(c.getString(1),fmt(c.getDouble(2))+" "+c.getString(3),"$ "+fmt(c.getDouble(4))+" / "+c.getString(3));c.close();}
 void rawDialog(){LinearLayout l=form();EditText n=e("اسم المادة"),q=e("الكمية"),u=e("الوحدة kg/L"),cost=e("تكلفة الوحدة USD");l.addView(n);l.addView(q);l.addView(u);l.addView(cost);new AlertDialog.Builder(this).setTitle("مادة أولية").setView(l).setPositiveButton("حفظ",(d,w)->{try{db.addRaw(n.getText().toString(),Double.parseDouble(q.getText().toString()),u.getText().toString(),Double.parseDouble(cost.getText().toString()));manufacturing();}catch(Exception x){toast("راجع البيانات");}}).setNegativeButton("إلغاء",null).show();}
 void people(String title,String type){shell(title,"إدارة "+title+" محلياً");Cursor c=db.people(type);while(c.moveToNext())card(c.getString(1),c.getString(2)==null?"":c.getString(2),c.getString(3)==null?"":c.getString(3));c.close();btn("＋ إضافة",()->personDialog(title,type));}
 void personDialog(String title,String type){LinearLayout l=form();EditText n=e("الاسم"),p=e("الهاتف"),note=e("ملاحظات");l.addView(n);l.addView(p);l.addView(note);new AlertDialog.Builder(this).setTitle("إضافة إلى "+title).setView(l).setPositiveButton("حفظ",(d,w)->{db.addPerson(type,n.getText().toString(),p.getText().toString(),note.getText().toString());people(title,type);}).setNegativeButton("إلغاء",null).show();}
 void invoices(){shell("سجل الفواتير","آخر حركات البيع");Cursor c=db.salesLog();while(c.moveToNext())card("فاتورة #"+c.getLong(0),c.getString(1)+" × "+c.getInt(2),"$ "+fmt(c.getDouble(3)));c.close();}
 void settings(){shell("الإعدادات","Drops POS • بيانات محلية");card("سعر الصرف","1 USD = 90,000 LBP","العملة الأساسية USD مع عرض LBP");card("قاعدة البيانات","Offline","البيانات محفوظة على الجهاز");card("الإصدار","Full build","نسخة التطوير الشاملة");}
 void expenses(){shell("المصاريف","تسجيل المصروفات اليومية");card("مصاريف اليوم","$ "+fmt(db.todayExpenses()),"محفوظة محلياً");btn("＋ تسجيل مصروف",()->expenseDialog());}
 void expenseDialog(){LinearLayout l=form();EditText n=e("البيان"),a=e("المبلغ USD");l.addView(n);l.addView(a);new AlertDialog.Builder(this).setTitle("مصروف جديد").setView(l).setPositiveButton("حفظ",(d,w)->{try{db.addExpense(n.getText().toString(),Double.parseDouble(a.getText().toString()));expenses();}catch(Exception x){toast("راجع المبلغ");}}).setNegativeButton("إلغاء",null).show();}
 void reports(){shell("التقارير","اليوم • الشهر • المخزون");double s=db.todaySales(),e=db.todayExpenses(),m=db.monthSales();card("مبيعات اليوم","$ "+fmt(s),lbp(s)+" LBP • "+db.todayCount()+" فاتورة");card("مبيعات هذا الشهر","$ "+fmt(m),lbp(m)+" LBP");card("مصاريف اليوم","$ "+fmt(e),lbp(e)+" LBP");card("صافي حركة اليوم","$ "+fmt(s-e),lbp(s-e)+" LBP");card("قيمة المخزون","$ "+fmt(db.stockValue()),"حسب سعر البيع الحالي");card("قطع المخزون",""+db.stockUnits(),db.lowCount()+" منتج منخفض");}
 LinearLayout form(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(16),dp(4),dp(16),0);return l;}EditText e(String h){EditText x=new EditText(this);x.setHint(h);x.setPadding(dp(8),dp(10),dp(8),dp(10));return x;}void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}String fmt(double d){return String.format(Locale.US,"%.2f",d);}String lbp(double d){return String.format(Locale.US,"%,.0f",d*90000);}
 static class DB extends SQLiteOpenHelper{DB(Context c){super(c,"drops.db",null,5);}public void onCreate(SQLiteDatabase d){d.execSQL("CREATE TABLE products(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,size TEXT,price REAL,qty INTEGER DEFAULT 0)");d.execSQL("CREATE TABLE invoices(id INTEGER PRIMARY KEY AUTOINCREMENT,total REAL,paid REAL,created INTEGER)");d.execSQL("CREATE TABLE sales(id INTEGER PRIMARY KEY AUTOINCREMENT,invoice_id INTEGER,product_id INTEGER,qty INTEGER,total REAL,created INTEGER)");d.execSQL("CREATE TABLE expenses(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,amount REAL,created INTEGER)");d.execSQL("CREATE TABLE people(id INTEGER PRIMARY KEY AUTOINCREMENT,type TEXT,name TEXT,phone TEXT,note TEXT)");d.execSQL("CREATE TABLE stock_moves(id INTEGER PRIMARY KEY AUTOINCREMENT,product_id INTEGER,qty INTEGER,type TEXT,created INTEGER)");d.execSQL("CREATE TABLE raw_materials(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,qty REAL,unit TEXT,cost REAL)");seed(d);}void seed(SQLiteDatabase d){String[][]a={{"Dishwashing","1L","2.56"},{"Dishwashing","4L","2.56"},{"Laundry Gel","1L","2.89"},{"Laundry Gel","4L","2.89"},{"Hand Soap","1L","3.11"},{"Hand Soap","4L","3.11"},{"Floor Cleaner","4L","2.22"}};for(String[]x:a)d.execSQL("INSERT INTO products(name,size,price,qty) VALUES(?,?,?,0)",x);}public void onUpgrade(SQLiteDatabase d,int a,int b){if(a<2)d.execSQL("CREATE TABLE IF NOT EXISTS people(id INTEGER PRIMARY KEY AUTOINCREMENT,type TEXT,name TEXT,phone TEXT,note TEXT)");if(a<3){d.execSQL("CREATE TABLE IF NOT EXISTS invoices(id INTEGER PRIMARY KEY AUTOINCREMENT,total REAL,paid REAL,created INTEGER)");try{d.execSQL("ALTER TABLE sales ADD COLUMN invoice_id INTEGER");}catch(Exception e){}}if(a<4)d.execSQL("CREATE TABLE IF NOT EXISTS stock_moves(id INTEGER PRIMARY KEY AUTOINCREMENT,product_id INTEGER,qty INTEGER,type TEXT,created INTEGER)");if(a<5)d.execSQL("CREATE TABLE IF NOT EXISTS raw_materials(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,qty REAL,unit TEXT,cost REAL)");}
 Cursor rawMaterials(){return getReadableDatabase().rawQuery("SELECT * FROM raw_materials ORDER BY name",null);}void addRaw(String n,double q,String u,double cost){ContentValues v=new ContentValues();v.put("name",n);v.put("qty",q);v.put("unit",u);v.put("cost",cost);getWritableDatabase().insert("raw_materials",null,v);}int rawCount(){return(int)scalar("SELECT COUNT(*) FROM raw_materials",null);}
 Cursor people(String type){return getReadableDatabase().rawQuery("SELECT * FROM people WHERE type=? ORDER BY name",new String[]{type});}void addPerson(String type,String n,String p,String note){ContentValues v=new ContentValues();v.put("type",type);v.put("name",n);v.put("phone",p);v.put("note",note);getWritableDatabase().insert("people",null,v);}Cursor salesLog(){return getReadableDatabase().rawQuery("SELECT sales.id,products.name,sales.qty,sales.total FROM sales LEFT JOIN products ON products.id=sales.product_id ORDER BY sales.created DESC LIMIT 100",null);}Cursor stockMoves(){return getReadableDatabase().rawQuery("SELECT stock_moves.id,products.name,products.size,stock_moves.qty,stock_moves.type FROM stock_moves LEFT JOIN products ON products.id=stock_moves.product_id ORDER BY stock_moves.created DESC LIMIT 150",null);}
 Cursor getProducts(){return getReadableDatabase().rawQuery("SELECT * FROM products ORDER BY name,size",null);}Cursor one(long id){return getReadableDatabase().rawQuery("SELECT * FROM products WHERE id=?",new String[]{""+id});}
 void addProduct(String n,String s,double p,int q){ContentValues v=new ContentValues();v.put("name",n);v.put("size",s);v.put("price",p);v.put("qty",q);getWritableDatabase().insert("products",null,v);}void updateProduct(long id,double p,int q){ContentValues v=new ContentValues();v.put("price",p);v.put("qty",q);getWritableDatabase().update("products",v,"id=?",new String[]{""+id});}void deleteProduct(long id){getWritableDatabase().delete("products","id=?",new String[]{""+id});}void addStock(long id,int q){SQLiteDatabase d=getWritableDatabase();d.execSQL("UPDATE products SET qty=qty+? WHERE id=?",new Object[]{q,id});d.execSQL("INSERT INTO stock_moves(product_id,qty,type,created) VALUES(?,?,?,?)",new Object[]{id,q,"IN",System.currentTimeMillis()});}
 boolean checkoutLegacy(Map<Long,Integer> cart){return checkout(cart,0)>0;}long checkout(Map<Long,Integer> cart,double paid){SQLiteDatabase d=getWritableDatabase();d.beginTransaction();try{double total=0;for(Map.Entry<Long,Integer>a:cart.entrySet()){Cursor c=d.rawQuery("SELECT price,qty FROM products WHERE id=?",new String[]{""+a.getKey()});if(!c.moveToFirst()){c.close();return 0;}double p=c.getDouble(0);int st=c.getInt(1),q=a.getValue();c.close();if(q<=0||st<q)return 0;total+=p*q;}long now=System.currentTimeMillis();ContentValues iv=new ContentValues();iv.put("total",total);iv.put("paid",paid);iv.put("created",now);long invoice=d.insert("invoices",null,iv);for(Map.Entry<Long,Integer>a:cart.entrySet()){Cursor c=d.rawQuery("SELECT price FROM products WHERE id=?",new String[]{""+a.getKey()});c.moveToFirst();double p=c.getDouble(0);c.close();int q=a.getValue();d.execSQL("UPDATE products SET qty=qty-? WHERE id=?",new Object[]{q,a.getKey()});d.execSQL("INSERT INTO sales(invoice_id,product_id,qty,total,created) VALUES(?,?,?,?,?)",new Object[]{invoice,a.getKey(),q,p*q,now});d.execSQL("INSERT INTO stock_moves(product_id,qty,type,created) VALUES(?,?,?,?)",new Object[]{a.getKey(),-q,"SALE",now});}d.setTransactionSuccessful();return invoice;}finally{d.endTransaction();}}
 void addExpense(String n,double a){getWritableDatabase().execSQL("INSERT INTO expenses(name,amount,created) VALUES(?,?,?)",new Object[]{n,a,System.currentTimeMillis()});}
 long start(){Calendar c=Calendar.getInstance();c.set(Calendar.HOUR_OF_DAY,0);c.set(Calendar.MINUTE,0);c.set(Calendar.SECOND,0);c.set(Calendar.MILLISECOND,0);return c.getTimeInMillis();}double scalar(String sql,String[]a){Cursor c=getReadableDatabase().rawQuery(sql,a);c.moveToFirst();double x=c.getDouble(0);c.close();return x;}double todaySales(){return scalar("SELECT COALESCE(SUM(total),0) FROM sales WHERE created>=?",new String[]{""+start()});}int todayCount(){return(int)scalar("SELECT COUNT(DISTINCT created) FROM sales WHERE created>=?",new String[]{""+start()});}double todayExpenses(){return scalar("SELECT COALESCE(SUM(amount),0) FROM expenses WHERE created>=?",new String[]{""+start()});}double stockValue(){return scalar("SELECT COALESCE(SUM(price*qty),0) FROM products",null);}int productCount(){return(int)scalar("SELECT COUNT(*) FROM products",null);}int lowCount(){return(int)scalar("SELECT COUNT(*) FROM products WHERE qty<=5",null);}int stockUnits(){return(int)scalar("SELECT COALESCE(SUM(qty),0) FROM products",null);}double monthSales(){Calendar c=Calendar.getInstance();c.set(Calendar.DAY_OF_MONTH,1);c.set(Calendar.HOUR_OF_DAY,0);c.set(Calendar.MINUTE,0);c.set(Calendar.SECOND,0);c.set(Calendar.MILLISECOND,0);return scalar("SELECT COALESCE(SUM(total),0) FROM sales WHERE created>=?",new String[]{""+c.getTimeInMillis()});}
 }
}